### ISSUE TITLE
webapp display mode throws error in wsl

### ISSUE THREAD

**Issue by HassanMojab** [antoine-coulon/skott#107]
Running in WSL (Windows Subsystem Linux) throws an error when trying to open the webapp URL:

```sh
$ skott --displayMode=webapp

 Running Skott from current directory: -

 Processed 183 files (1885.137ms)

 ✓ no circular dependencies found (depth=Infinity)

 Third-party dependencies: ❌

 --> Use --trackThirdPartyDependencies to enable tracking.

 Built-in dependencies: ❌

 --> Use --trackBuiltinDependencies to enable tracking.

 Type-level only dependencies: ✅

 Prefetching data... 

 💻 Opened skott webapp on http://127.0.0.1:41707

 Skott exited with code 1
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://127.0.0.1:41707' ]
}

Node.js v18.18.0
```

**Comment by antoine-coulon** [comment]
Hello @HassanMojab, thanks for the heads up!

It seems that it comes from an upstream problem on WSL https://github.com/microsoft/WSL/issues/8892. 
As I'm using a fork of [openurl](https://github.com/rauschma/openurl/blob/fa7447eaba8161da5b00281a15e35c911369ce17/openurl.js#L13) I will do two things:

1. Try to find a workaround for WSL to be able to keep that auto open behavior (some workarounds are [discussed here](https://github.com/kubeshark/kubeshark/issues/1024)). The thing is I'm not running WSL myself, so will be hard for me to reproduce and be sure to fix the problem.

2. Fix the uncaught exception in the library I'm using that [should be handled properly and not make the process crash](https://github.com/antoine-coulon/skott/blob/61c0dc5edfdbe1214dda6a3d9debb78cbed845f1/packages/skott/bin/ui/webapp.ts#L106) (upstream, not in skott). This would have for consequence to not open the browser automatically but would allow the application to be accessible anyway.

**Comment by antoine-coulon** [comment]
Just released an attempt to a fix for WSL in `0.30.1`. 

In the best scenario `wslview` works as expected and the browser will be automatically opened. 

In the worst scenario, `wslview` does not work but now the error is properly managed so the process won't crash and you'll be able to access the application manually. If you have any suggestion to properly use `wslview` or an alternative as I'm not familiar at all with it, feel free to re-open the issue and keep the discussion going on.

Thanks

**Comment by antoine-coulon** [comment]
@HassanMojab, I just released an attempt to a fix for WSL in `0.30.1`. 

In the best scenario `wslview` works as expected and the browser will be automatically opened. 

In the worst scenario, `wslview` does not work but now the error is properly managed so the process won't crash and you'll be able to access the application manually. If you have any suggestion to properly use `wslview` or an alternative as I'm not familiar at all with it, feel free to re-open the issue and keep the discussion going on.

Thanks

**Comment by HassanMojab** [comment]
The `wslview` is not installed on wsl by default. I've found this command for opening a URL on the Windows default browser from wsl:
```sh
cmd.exe /C start "https://example.com" > /dev/null 2>&1
```

**Comment by antoine-coulon** [comment]
Ah fml I was too confident about it 😅 I'll add your cmd.exe in another PR as a primary target when being in WSL. Thanks for the hint!

**Comment by antoine-coulon** [comment]
Hey again @HassanMojab,

Just released `0.30.2` switching for `cmd.exe` instead of `wslview`. Could you please confirm me that it now works well please? Thanks!

**Comment by HassanMojab** [comment]
It works! the browser opens with the given URL `127.0.0.1:<port>`

But unfortunately, there is still an issue :( 127.0.0.1 is considered as localhost in linux, but not in windows. So the ports of wsl are forwarded to the localhost of the windows and can be accessed by `localhost:<port>` but not by `127.0.0.1:<port>`.

I think you simply can use localhost instead of 127.0.0.1 in the code like other cross-platform applications, and it should solve this problem.

**Comment by antoine-coulon** [comment]
Glad to hear that the auto opening is working as expected on WSL :) 

About localhost, I was not aware of that and I thought WSL would manage this transparently. Thanks for the hint! I just changed `127.0.0.1` to `localhost` on all platforms in `0.30.3`. 

Could you please test it and confirm me that it now fully works? Thanks again for your reactivity and contribution, highly appreciate it

**Comment by HassanMojab** [comment]
Now it fully works!

**Comment by antoine-coulon** [comment]
Thanks again for confirming that @HassanMojab!
